"use strict";

((root) => {

root.ActionTypes = {
  DESCRIPTION_INPUT:                "DESCRIPTION_INPUT",
  DETECT_SHARED_LINK:               "DETECT_SHARED_LINK",
  DISMISS_SHARED_LINK:              "DISMISS_SHARED_LINK",
  FETCHED_BROADCAST_PLACARD_COUNTS: "FETCHED_BROADCAST_PLACARD_COUNTS",
  FETCHED_CHANNELS:                 "FETCHED_CHANNELS",
  FETCHED_PROCURE_POST_ASSETS:      "FETCHED_PROCURE_POST_ASSETS",
  FETCHED_PUBLISHABLE_GROUPS:       "FETCHED_PUBLISHABLE_GROUPS",
  FETCHED_PUBLISHABLE_USERS:        "FETCHED_PUBLISHABLE_USERS",
  FETCHED_PUBLISHABLE_SUBCHANNELS:  "FETCHED_PUBLISHABLE_SUBCHANNELS",
  MESSAGE_INPUT:                    "MESSAGE_INPUT",
  PICTURE_INPUT:                    "PICTURE_INPUT",
  POST_MODE_CHANGE:                 "POST_MODE_CHANGE",
  RECIPIENT_SELECTION_ITEM_CHANGE:  "RECIPIENT_SELECTION_ITEM_CHANGE",
  RECIPIENTS_DROPDOWN_TOGGLE:       "RECIPIENTS_DROPDOWN_TOGGLE",
  REFOCUS_INPUT:                    "REFOCUS_INPUT",
  TITLE_INPUT:                      "TITLE_INPUT",
};

})(window);
